### PR TITLE
IntelliJDeodorant feature envy

### LINKED ISSUE #1: Code Smell: Feature Envy

### PR DESCRIPTION
**Pull request by OwenBC**
These changes are based on the suggestions from the IntelliJ plugin IntelliJDeodorant for the feature envy code smell.

closes #1

### CODE REVIEW

**Comment by OwenBC** [comment]
NOTE: Still working on this, don't merge yet!

**Comment by OwenBC** [comment]
### [Refactor: merged CharacterChange class into Player](https://github.com/realjaidhaliwal/JAdventure-Refactoring/pull/5/commits/b8232395b120314d335d055cdb0c645c88d915bd)

Combined the [checkForCharacter](https://github.com/realjaidhaliwal/JAdventure-Refactoring/blob/b8232395b120314d335d055cdb0c645c88d915bd/src/main/java/com/jadventure/game/entities/Player.java#L552) and [trigger](https://github.com/realjaidhaliwal/JAdventure-Refactoring/blob/b8232395b120314d335d055cdb0c645c88d915bd/src/main/java/com/jadventure/game/entities/Player.java#L506) methods of the CharacterChange class into the Player class. These methods comprised the entirety of the CharacterChange class, so the class is deleted. The CharacterChange class was only a extension of functionality of the Player class and so could fit better as methods of the class.

No test coverage, so I've added [a test](https://github.com/realjaidhaliwal/JAdventure-Refactoring/pull/5/files#diff-46ceae8f46bb71df80a2d5dd9e3af0deeddf38eda33f0906d5cc3121c4866cc5) case in PlayerTest.

**Comment by OwenBC** [comment]
### [Refactor: moved attack method from BattleMenu to Entity](https://github.com/realjaidhaliwal/JAdventure-Refactoring/pull/5/commits/ca70d6e7a1204c47dfab6cc8e92aaa1b85ef4d4e)

The attack method involves the data of two entities and nothing from the battle menu class, specifically a player and an opponent (npc or monster). Therefore it makes sense to move this two the parent class of all three, Entity. 

Added [test case coverage](https://github.com/realjaidhaliwal/JAdventure-Refactoring/pull/5/commits/7f686623aca2e06c7235f0572d1f21179a9619b4).

**Comment by OwenBC** [comment]
### [Refactor: moved viewStats, promptEquip, and promptUnequip methods from BattleMenu to Player](https://github.com/realjaidhaliwal/JAdventure-Refactoring/pull/5/commits/b353be9397d6051e1afc823f8187a47e21e2293e)

These method involve the data of two entities and nothing from the battle menu class. These methods need not be specific to the BattleMenu and can now be used from other classes utilizing the Player class in the future. 

These methods utilize player input, and frankly I don't know how to test that. Instead, I've tested this manually to confirm proper refactoring. Given the simplicity of these methods, I believe this is adequate.

**Review by vijaivir — APPROVED** [review]
I also refactored 2 methods from CharacterChange.java and ConversationManager.java so merging my branch after yours might result in some conflicts. If you are done we can merge this and I will update my changes.

**Comment by OwenBC** [comment]
> I also refactored 2 methods from CharacterChange.java and ConversationManager.java so merging my branch after yours might result in some conflicts. If you are done we can merge this and I will update my changes.

Sounds good, I'll go ahead and merge this now

**Comment by OwenBC** [comment]
@realjaidhaliwal Let me know if you're having any issues merging changes, I can help out with that

**Comment by vijaivir** [comment]
> @realjaidhaliwal Let me know if you're having any issues merging changes, I can help out with that

Thanks, took me a few minutes but I figured it out! :)

**Pull request merged**
